setwd("E:/learning_R")
reddit <- read.csv("reddit.csv")
table(reddit$employment.status)
summary(reddit)
str(reddit)
age_levels<-levels(reddit$age.range)
income_levels<-levels(reddit$income.range)
library(ggplot2)
reddit$age.range<-ordered(reddit$age.range,levels=c("Under 18","18-24","25-34","35-44","45-54","55-64","65 of Above"))
qplot(data=reddit,x=age.range)
