---
title: "exploring1"
author: "tang"
date: "2016年8月6日"
output: html_document
---

```{r setup, include=FALSE}
library(base)
library(stats)
library(dplyr)
library(ggplot2)
library(reshape2)
library(psych)
library(RColorBrewer) 
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
setwd("D:/github/udacity_data_analyse/project6")
df<- read.csv("pisa2012.csv",encoding="UTF-8")

```

```{r}

# de<- function(x){
#   invisible(capture.output(mm<-str(x)))
#   nn<-summary(x)
#   result<-list(mm=mm,nn=nn)
#   return(result)
# 
# }
de <- function(x) {
      c(str = str(x), summary = summary(x))
}
```

```{r}
ggplot(aes(x=ST26Q04,y=OUTHOURS),data = subset(df,!is.na(df$OUTHOURS)))+
  geom_boxplot()+
  ylim(0,25)
ggplot(aes(x=ST37Q05,y=ST57Q01),data = subset(df,!is.na(df$ST37Q05)))+#x is Math Self-Efficacy - Solving Equation 1
  geom_boxplot()                                   #y is Out-of-School Study Time - Homework
```

```{r}
###construct new data frame
interest_index_begin<-which(colnames(df)=="PV1MATH")
len<-38
interest_index_end<-interest_index_begin+len-1
#apply(df[interest_index_begin:interest_index_end],2,de)
math_names=colnames(df)[interest_index_begin:interest_index_end]
df$math_score <- rowMeans(subset(df, select = math_names), na.rm = FALSE)
###########################################
interest_index_begin<-which(colnames(df)=="PV1READ")
len<-5
interest_index_end<-interest_index_begin+len-1
#apply(df[interest_index_begin:interest_index_end],2,de)
reading_names=colnames(df)[interest_index_begin:interest_index_end]
df$reading_score <- rowMeans(subset(df, select = reading_names), na.rm = FALSE)
###############################
interest_index_begin<-which(colnames(df)=="PV1SCIE")
len<-5
interest_index_end<-interest_index_begin+len-1
#apply(df[interest_index_begin:interest_index_end],2,de)
science_names=colnames(df)[interest_index_begin:interest_index_end]
df$science_score <- rowMeans(subset(df, select = science_names), na.rm = FALSE)
############################
df$ST88Q01 <-ordered(
  df$ST88Q01, levels = c("Strongly disagree", "Disagree","Agree","Strongly agree"))

df$ST28Q01 <-ordered(
  df$ST28Q01, levels = c("0-10 books ","11-25 books ","26-100 books ","101-200 books ","201-500 books ","More than 500 books"))
df$IMMIG <-ordered(
  df$IMMIG, levels = c( "Native","First-Generation","Second-Generation"))
df$HEDRES <-ordered(
  df$HEDRES, levels = c( "Native","First-Generation","Second-Generation"))
############################
interest_index_begin<-which(colnames(df)=="IC08Q01")
len<-8
interest_index_end<-interest_index_begin+len-1
apply(df[interest_index_begin:interest_index_end],2,de)
###########################################
ggplot(aes(x=IMMIG,y=math_score),
       data=subset(df,!is.na(ST88Q01) & !is.na(math_score)& !is.na(IMMIG)))+
  geom_point(alpha=0.2,aes(color=ST88Q01),position = "jitter")
ggplot(aes(x=IMMIG,y=math_score),data = subset(df,!is.na(math_score)& !is.na(IMMIG)))+
  geom_boxplot()+
  ylim(250,650)
ggplot(aes(x=ST88Q01,y=math_score),data = subset(df,!is.na(math_score)& !is.na(ST88Q01)))+
  geom_boxplot()
ggplot(aes(x=IC08Q11,y=math_score),data = subset(df,!is.na(math_score)& !is.na(IC08Q11)))+
  geom_boxplot()
ggplot(aes(x=IC08Q11,y=reading_score),data = subset(df,!is.na(reading_score)& !is.na(IC08Q11)))+
  geom_boxplot()
ggplot(aes(x=ST88Q01,y=reading_score),data = subset(df,!is.na(reading_score)& !is.na(ST88Q01)))+
  geom_boxplot()

out=out[, !(colnames(out) %in% c("df.math_score"))]
interested_columns<-c("math_score","reading_score","science_score","WEALTH","PARED_cut1","HISCED","IMMIG","MISCED","FISCED","ST28Q01","ENTUSE","ESCS","HEDRES","HOMEPOS")
write.csv(out,file="D:/github/udacity_data_analyse/project6/data.csv")
```

```{r}
interest_index_begin<-which(colnames(df)=="ST93Q01")
len<-5
interest_index_end<-interest_index_begin+len-1
apply(df[interest_index_begin:interest_index_end],2,de)

```

点图：Y 是人群各种平均score，颜色是父母受教育年限PARED（种类要多），size是population大小count，x可以（WEALTH,BELONG,COGACT,ENTUSE）must averagable

```{r}
df$PARED_cut1<-cut(df$PARED,c(2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18))
df$PARED_cut2<-cut(df$PARED,c(2,7,10,11,12,13,14,15,16,17,18))
ggplot(aes(x=WEALTH,y=math_score),data = subset(df,!is.na(math_score)& !is.na(WEALTH)))+
  geom_point()

ggplot(aes(x=PARED_cut2,y=math_score),
       data=subset(df,!is.na(PARED_cut2) & !is.na(math_score)& !is.na(ST04Q01)))+
  geom_point(alpha=0.2,aes(color=ST04Q01),position = "jitter")

ggplot(aes(x=Category,y=x),
       data=manual)+
  geom_point()
```

So, x:WEALTH,ENTUSE,ESCS,HEDRES,HOMEPOS     y:reading_score , science_score, math_score, group:PARED_cut1,HISCED,IMMIG,MISCED,FISCED,ST28Q01

```{r}
ggplot(aes(x=science_score,y=math_score),data = subset(df,!is.na(math_score)& !is.na(science_score)))+
  geom_point(alpha=0.01,color='blue')

```

```{r}
###get the data done
#aggregate(x$Frequency, by=list(Category=x$Category), FUN=sum)
out.aggregate.PARED_cut1<-out%>% # here i construct new data frame, both long and wide, for later use
  filter(!is.na(math_score))%>%             # filter out the observations with missed values
  filter(!is.na(WEALTH))%>%
  filter(!is.na(PARED_cut1))%>%
  group_by(PARED_cut1)%>%
  summarise(mean_math=mean(math_score),
            mean_science=mean(science_score),
            mean_reading=mean(reading_score),
            mean_wealth=mean(WEALTH),
            n=n())%>%
  ungroup()#%>%
  #arrange(Occupation)
#with(out.aggregate, symbols(x=mean_wealth, y=mean_math, circles=n, inches=1,
 #                           bg=PARED_cut1, fg=NULL))

mycolors = c(brewer.pal(name="Dark2", n = 8), brewer.pal(name="Paired", n = 10))
ggplot(aes(x=mean_wealth,y=mean_math,color=PARED_cut1,size=n),data=out.aggregate.PARED_cut1)+
  geom_point(alpha=0.8)+
  #scale_size(range = c(2, 50))+
  scale_size_area(max_size = 50)+
  #scale_colour_brewer(palette=1)
  scale_color_manual(values = mycolors)


```

```{r}
df$ST28Q01 <-ordered(
  df$ST28Q01, levels = c("0-10 books ", "11-25 books ","26-100 books ","101-200 books ","201-500 books ","More than 500 books"))
out.aggregate.ST28Q01<-df%>% # here i construct new data frame, both long and wide, for later use
  filter(!is.na(science_score))%>%
  filter(!is.na(math_score))%>%
  filter(!is.na(reading_score))%>%   # filter out the observations with missed values
  filter(!is.na(WEALTH))%>%
  filter(!is.na(ENTUSE))%>%
  filter(!is.na(HOMEPOS))%>%
  filter(!is.na(ST28Q01))%>%
  group_by(ST28Q01)%>%
  summarise(mean_math=mean(math_score),
            mean_reading=mean(reading_score),
            mean_science=mean(science_score),
            mean_wealth=mean(WEALTH),
            mean_entertainment=mean(ENTUSE),
            mean_possessions=mean(HOMEPOS),
            size=n())%>%
  ungroup()
out.aggregate.ST28Q01['mean_wealth']<-out.aggregate.ST28Q01['mean_wealth']+2
out.aggregate.ST28Q01['mean_possessions']<-out.aggregate.ST28Q01['mean_possessions']+2
out.aggregate.ST28Q01['mean_entertainment']<-out.aggregate.ST28Q01['mean_entertainment']+2
colnames(out.aggregate.ST28Q01)[which(names(out.aggregate.ST28Q01) == "ST28Q01")] <- "books"
write.csv(out.aggregate.ST28Q01,file="D:/github/udacity_data_analyse/project6/data_ST28Q01.csv")

df$HISCED <-ordered(
  df$HISCED, levels = c("None" , "ISCED 1","ISCED 2","ISCED 3B, C","ISCED 3A","ISCED 4","ISCED 5B","ISCED 5A, 6"))
out.aggregate.HISCED<-df%>% # here i construct new data frame, both long and wide, for later use
  filter(!is.na(science_score))%>%
  filter(!is.na(math_score))%>%
  filter(!is.na(reading_score))%>%   # filter out the observations with missed values
  filter(!is.na(WEALTH))%>%
  filter(!is.na(ENTUSE))%>%
  filter(!is.na(HOMEPOS))%>%
  filter(!is.na(HISCED))%>%
  group_by(HISCED)%>%
  summarise(mean_math=mean(math_score),
            mean_reading=mean(reading_score),
            mean_science=mean(science_score),
            mean_wealth=mean(WEALTH),
            mean_entertainment=mean(ENTUSE),
            mean_possessions=mean(HOMEPOS),
            size=n())%>%
  ungroup()
out.aggregate.HISCED['mean_wealth']<-out.aggregate.HISCED['mean_wealth']+2
out.aggregate.HISCED['mean_possessions']<-out.aggregate.HISCED['mean_possessions']+2
out.aggregate.HISCED['mean_entertainment']<-out.aggregate.HISCED['mean_entertainment']+2
colnames(out.aggregate.HISCED)[which(names(out.aggregate.HISCED) == "HISCED")] <- "Parents_education_level"
write.csv(out.aggregate.HISCED,file="D:/github/udacity_data_analyse/project6/data_HISCED.csv")


#df$PARED_cut1 <-ordered(
#  df$PARED_cut1, levels = c("None" , "ISCED 1","ISCED 2","ISCED 3B, C","ISCED 3A","ISCED 4","ISCED 5B","ISCED 5A, 6"))
out.aggregate.PARED_cut1<-df%>% # here i construct new data frame, both long and wide, for later use
  filter(!is.na(science_score))%>%
  filter(!is.na(math_score))%>%
  filter(!is.na(reading_score))%>%   # filter out the observations with missed values
  filter(!is.na(WEALTH))%>%
  filter(!is.na(ENTUSE))%>%
  filter(!is.na(HOMEPOS))%>%
  filter(!is.na(PARED_cut1))%>%
  group_by(PARED_cut1)%>%
  summarise(mean_math=mean(math_score),
            mean_reading=mean(reading_score),
            mean_science=mean(science_score),
            mean_wealth=mean(WEALTH),
            mean_entertainment=mean(ENTUSE),
            mean_possessions=mean(HOMEPOS),
            size=n())%>%
  ungroup()
out.aggregate.PARED_cut1['mean_wealth']<-out.aggregate.PARED_cut1['mean_wealth']+2
out.aggregate.PARED_cut1['mean_possessions']<-out.aggregate.PARED_cut1['mean_possessions']+2
out.aggregate.PARED_cut1['mean_entertainment']<-out.aggregate.PARED_cut1['mean_entertainment']+2
colnames(out.aggregate.PARED_cut1)[which(names(out.aggregate.PARED_cut1) == "PARED_cut1")] <- "Parents_education_year"
write.csv(out.aggregate.PARED_cut1,file="D:/github/udacity_data_analyse/project6/data_PARED_cut1.csv")

df$IMMIG <-ordered(
  df$IMMIG, levels = c( "Native","First-Generation","Second-Generation"))
out.aggregate.IMMIG<-df%>% # here i construct new data frame, both long and wide, for later use
  filter(!is.na(science_score))%>%
  filter(!is.na(math_score))%>%
  filter(!is.na(reading_score))%>%   # filter out the observations with missed values
  filter(!is.na(WEALTH))%>%
  filter(!is.na(ENTUSE))%>%
  filter(!is.na(HOMEPOS))%>%
  filter(!is.na(IMMIG))%>%
  group_by(IMMIG)%>%
  summarise(mean_math=mean(math_score),
            mean_reading=mean(reading_score),
            mean_science=mean(science_score),
            mean_wealth=mean(WEALTH),
            mean_entertainment=mean(ENTUSE,na.rm = TRUE),
            mean_possessions=mean(HOMEPOS),
            size=n())%>%
  ungroup()
out.aggregate.IMMIG['mean_wealth']<-out.aggregate.IMMIG['mean_wealth']+2
out.aggregate.IMMIG['mean_possessions']<-out.aggregate.IMMIG['mean_possessions']+2
out.aggregate.IMMIG['mean_entertainment']<-out.aggregate.IMMIG['mean_entertainment']+2
colnames(out.aggregate.IMMIG)[which(names(out.aggregate.IMMIG) == "IMMIG")] <- "Immigration_status"
write.csv(out.aggregate.IMMIG,file="D:/github/udacity_data_analyse/project6/data_IMMIG.csv")
```
PARED_cut1,HISCED,IMMIG,MISCED,FISCED,ST28Q01
```{r}

ggplot(aes(x=mean_home_edu_resource,y=mean_science,color=ST28Q01,size=n),data=out.aggregate.ST28Q01)+
  geom_point(alpha=0.8)+
  #scale_size(range = c(10.77, 50))+
  scale_size_area(max_size = 50)+
  scale_color_manual(values = mycolors)

out.aggregate.IMMIG<-out%>% # here i construct new data frame, both long and wide, for later use
  filter(!is.na(math_score))%>%             # filter out the observations with missed values
  filter(!is.na(WEALTH))%>%
  filter(!is.na(ST28Q01))%>%
  group_by(IMMIG)%>%
  summarise(mean_math=mean(math_score),
            mean_wealth=mean(WEALTH),
            n=n())%>%
  ungroup()

ggplot(aes(x=mean_wealth,y=mean_math,color=IMMIG,size=n),data=out.aggregate.IMMIG)+
  geom_point(alpha=0.8)+
  scale_size_area(max_size = 50)+
  scale_color_manual(values = mycolors)

```

```{r}
#clean data
out.cleaned<-out[,c('math_score','science_score','reading_score','WEALTH','ST28Q01')]%>% # here i construct new data frame, both long and wide, for later use
  filter(!is.na(math_score))%>%             # filter out the observations with missed values
  filter(!is.na(WEALTH))%>%
  filter(!is.na(ST28Q01))%>%
  filter(!is.na(science_score))%>%
  filter(!is.na(reading_score))

```
```{r}
out.aggregate.IMMIG2<-df%>% # here i construct new data frame, both long and wide, for later use
  filter(!is.na(science_score))%>%
  filter(!is.na(math_score))%>%
  filter(!is.na(reading_score))%>%   # filter out the observations with missed values
  filter(!is.na(WEALTH))%>%
  filter(!is.na(IMMIG))%>%
  group_by(IMMIG)%>%
  summarise(mean_math=mean(math_score),
            mean_reading=mean(reading_score),
            mean_science=mean(science_score),
            mean_wealth=mean(WEALTH),
            mean_entertainment=mean(ENTUSE,na.rm = TRUE),
            mean_possessions=mean(HOMEPOS),
            size=n())%>%
  ungroup()

```

